WIDTH: int = 800
HEIGHT: int = 600
BG_COLOR: str = "Black"
IN_GAME: bool = True
BORDER_WIDTH: int = 1 
MAX_Y: int = ((HEIGHT / 2) - BORDER_WIDTH )
MIN_Y: int = -abs((HEIGHT / 2)  - BORDER_WIDTH ) 
BAT_HEIGHT: int = 10
BAT_WIDTH: int = 1
# BAT_SHAPE:str ="strech_wid" 